/**
 * F10 Partner Performance Dashboard — Launcher (Node.js)
 * - Fetches fresh data from Redash → saves dashboard_data.js
 * - Starts a local HTTP server at http://localhost:3456
 * - Opens dashboard in browser (localhost so Google cookies work for Trainer tab)
 */

const https  = require('https');
const http   = require('http');
const fs     = require('fs');
const path   = require('path');
const { exec } = require('child_process');

const REDASH_URL    = 'jarvis.urbanclap.com';
const QUERY_ID      = 548736;
const API_KEY       = 'FNsr3ZwNahnzSuaIYZrKKJUhRdS6nzhpdBq5s6P6';
const DIR           = __dirname;
const DATA_JS       = path.join(DIR, 'dashboard_data.js');
const TRAINER_JS    = path.join(DIR, 'trainer_data.js');
const TRAINER_CSV   = path.join(DIR, 'trainer_sheet.csv');
const DASHBOARD     = 'F10_Partner_Performance_Dashboard.html';
const PORT          = 3456;

// ── Redash API helpers ───────────────────────────────────────
function apiRequest(method, urlPath, body) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const options = {
      hostname: REDASH_URL,
      path: urlPath,
      method: method,
      rejectUnauthorized: false,
      headers: {
        'Authorization': `Key ${API_KEY}`,
        'Content-Type': 'application/json',
        ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {})
      }
    };
    const req = https.request(options, res => {
      let raw = '';
      res.on('data', chunk => raw += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(raw)); }
        catch(e) { reject(new Error('Bad JSON: ' + raw.slice(0, 200))); }
      });
    });
    req.on('error', (e) => { console.error('   Network error:', e.message); reject(e); });
    req.setTimeout(30000, () => { req.destroy(); reject(new Error('Timeout')); });
    if (data) req.write(data);
    req.end();
  });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function triggerRefresh() {
  try {
    const res = await apiRequest('POST', `/api/queries/${QUERY_ID}/results`, { parameters: {} });
    return res.job && res.job.id;
  } catch(e) { return null; }
}

async function pollJob(jobId, timeoutMs = 600000) {
  process.stdout.write('   Waiting for query to finish (up to 10 min for full-year data)');
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await apiRequest('GET', `/api/jobs/${jobId}`);
      const job = res.job || {};
      if (job.status === 3) { console.log(' done ✅'); return job.query_result_id; }
      if (job.status === 4) { console.log(` failed ❌ (error: ${job.error})`); return null; }
      process.stdout.write('.');
      await sleep(5000);
    } catch(e) { await sleep(5000); }
  }
  console.log(' timed out ⏱ — will try cached results anyway');
  return null;
}

async function getResultById(resultId) {
  try {
    const res = await apiRequest('GET', `/api/query_results/${resultId}`);
    const qr  = res.query_result || {};
    const rows = (qr.data || {}).rows || [];
    console.log(`   Fetched ${rows.length} rows from result #${resultId}`);
    return { rows, retrieved_at: qr.retrieved_at || '' };
  } catch(e) { return null; }
}

async function getCached() {
  try {
    const res = await apiRequest('GET', `/api/queries/${QUERY_ID}/results.json`);
    const qr  = res.query_result || {};
    const rows = (qr.data || {}).rows || [];
    console.log(`   Fetched ${rows.length} rows from cached result`);
    return { rows, retrieved_at: qr.retrieved_at || '' };
  } catch(e) { return null; }
}

function normalize(rows) {
  const required = [
    'APPROVAL_MONTH','PROVIDER_ID','PROVIDER_NAME','RATING','HIDDEN_RATING',
    'RATING_FINAL','CUSTOMER_REQUEST_ID','CUSTOMER_REVIEW','NPS_COMMENTS',
    'SERVICE_RATING','CITY','HUB','DURATION','FREQ_TYPE','USER_TYPE','BDATE',
    'REVISED_START_AT','REVISED_START_TIME_ELIGIBLE','CORRECT_START_AT',
    'START_TIME_DIFF','LATE_SHOW_STATUS','R'
  ];
  return rows.map(row => {
    const nr = {};
    for (const [k, v] of Object.entries(row)) {
      nr[k.toUpperCase()] = (v === null || v === undefined) ? '' : String(v);
    }
    for (const f of required) { if (!(f in nr)) nr[f] = ''; }
    return nr;
  });
}

function saveData(rows, retrieved_at) {
  const nr = normalize(rows);
  let dateStr;
  try {
    const dt = new Date(retrieved_at);
    dateStr = dt.toUTCString().replace(' GMT', ' UTC');
  } catch(e) {
    dateStr = new Date().toUTCString().replace(' GMT', ' UTC');
  }
  const content = [
    '// Auto-generated by F10 Dashboard Launcher — do not edit manually',
    `// Last updated: ${dateStr}`,
    `const RAW = ${JSON.stringify(nr)};`,
    `const DATA_DATE = "${dateStr}";`,
    ''
  ].join('\n');
  fs.writeFileSync(DATA_JS, content, 'utf8');
  console.log(`   ✅ ${nr.length} rows saved  |  ${dateStr}`);

  // Build self-contained hosted version
  try {
    const htmlSrc = path.join(DIR, 'F10_Partner_Performance_Dashboard.html');
    const hostedDest = path.join(DIR, 'F10_Dashboard_Hosted.html');
    const retrainingPath = path.join(DIR, 'retraining_dashboard.html');
    if (fs.existsSync(htmlSrc)) {
      let html = fs.readFileSync(htmlSrc, 'utf8');
      // Inline dashboard data
      html = html.replace(
        '<script src="dashboard_data.js"></script>',
        `<script>\n${content}\n</script>`
      );
      // Inline retraining dashboard as blob URL
      if (fs.existsSync(retrainingPath)) {
        const retrainingHtml = fs.readFileSync(retrainingPath, 'utf8');
        const escaped = retrainingHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${').replace(/<\/script>/gi, '<\\/script>');
        const blobScript = `<script>\nconst RETRAINING_HTML = \`${escaped}\`;\n</script>`;
        html = html.replace('</head>', blobScript + '\n</head>');
        html = html.replace(
          "document.getElementById('retrainingFrame').src = 'retraining_dashboard.html';",
          `(function(){const b=new Blob([RETRAINING_HTML],{type:'text/html'});document.getElementById('retrainingFrame').src=URL.createObjectURL(b);})();`
        );
        html = html.replace(
          "frame.src = 'retraining_dashboard.html';",
          "frame.src = (typeof RETRAINING_HTML !== 'undefined') ? URL.createObjectURL(new Blob([RETRAINING_HTML],{type:'text/html'})) : 'retraining_dashboard.html';"
        );
        console.log('   🔁 Retraining dashboard inlined into hosted version');
      }
      fs.writeFileSync(hostedDest, html, 'utf8');
      const kb = (Buffer.byteLength(html, 'utf8') / 1024).toFixed(0);
      console.log(`   📦 F10_Dashboard_Hosted.html built (${kb} KB)`);
    }
  } catch(e) {
    console.log('   ⚠️  Could not build hosted version:', e.message);
  }
}

// ── Local HTTP server ────────────────────────────────────────
const MIME = {
  '.html': 'text/html',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
};

function startServer() {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const cors = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type'
      };

      // Save Apps Script URL to trainer_config.js
      if (req.method === 'POST' && req.url === '/save-config') {
        let body = '';
        req.on('data', c => body += c);
        req.on('end', () => {
          try {
            const { url } = JSON.parse(body);
            const configPath = path.join(DIR, 'trainer_config.js');
            fs.writeFileSync(configPath,
              `// Auto-saved by F10 Dashboard — do not edit manually\nvar TRAINER_APPS_SCRIPT_URL = ${JSON.stringify(url)};\n`,
              'utf8');
            console.log('   ✅ Apps Script URL saved to trainer_config.js');
            res.writeHead(200, { 'Content-Type': 'application/json', ...cors });
            res.end(JSON.stringify({ ok: true }));
          } catch(e) {
            res.writeHead(500, { 'Content-Type': 'application/json', ...cors });
            res.end(JSON.stringify({ error: e.message }));
          }
        });
        return;
      }

      if (req.method === 'OPTIONS') {
        res.writeHead(204, cors); res.end(); return;
      }

      // Serve files from the dashboard directory
      let filePath = path.join(DIR, req.url === '/' ? DASHBOARD : req.url.split('?')[0]);
      // Security: only serve files within DIR
      if (!filePath.startsWith(DIR)) { res.writeHead(403); res.end(); return; }
      fs.readFile(filePath, (err, data) => {
        if (err) {
          res.writeHead(404, {'Content-Type': 'text/plain'});
          res.end('Not found');
          return;
        }
        const ext = path.extname(filePath).toLowerCase();
        const ct  = MIME[ext] || 'application/octet-stream';
        res.writeHead(200, {'Content-Type': ct, ...cors});
        res.end(data);
      });
    });
    server.listen(PORT, '127.0.0.1', () => {
      console.log(`   🌐 Local server running at http://localhost:${PORT}`);
      resolve(server);
    });
    server.on('error', e => {
      if (e.code === 'EADDRINUSE') {
        console.log(`   ⚠️  Port ${PORT} in use — dashboard may already be open`);
        resolve(null);
      } else reject(e);
    });
  });
}

// ── CSV → trainer_data.js ────────────────────────────────────
function parseCsv(text) {
  const lines = text.split(/\r?\n/).filter(l => l.trim());
  if (lines.length < 2) return [];
  function splitLine(line) {
    const fields = []; let cur = '', inQ = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') { if (inQ && line[i+1] === '"') { cur += '"'; i++; } else inQ = !inQ; }
      else if (ch === ',' && !inQ) { fields.push(cur); cur = ''; }
      else cur += ch;
    }
    fields.push(cur); return fields;
  }
  const headers = splitLine(lines[0]).map(h => h.trim());
  return lines.slice(1).map(line => {
    const vals = splitLine(line);
    const obj = {};
    headers.forEach((h, i) => { obj[h] = (vals[i] || '').trim(); });
    return obj;
  }).filter(row => Object.values(row).some(v => v));
}

function processTrainerCsv() {
  // Accept trainer_sheet.csv or trainer_sheet.csv.csv (Windows double-extension)
  const csvPath = [TRAINER_CSV, TRAINER_CSV + '.csv'].find(p => fs.existsSync(p));
  if (!csvPath) return false;
  const TRAINER_CSV_FOUND = csvPath;
  try {
    const text = fs.readFileSync(TRAINER_CSV_FOUND, 'utf8');
    const rawRows = parseCsv(text);
    if (!rawRows.length) return false;

    // Normalize: pick the right column regardless of exact header name
    const get = (row, ...keys) => {
      for (const k of keys) {
        // exact match
        if (row[k] !== undefined && String(row[k]).trim() !== '') return String(row[k]).trim();
        // case-insensitive match
        const found = Object.keys(row).find(rk => rk.trim().toLowerCase() === k.toLowerCase());
        if (found && String(row[found]).trim() !== '') return String(row[found]).trim();
      }
      return '';
    };

    const rows = rawRows
      .filter(r => get(r, 'PROVIDER_ID'))
      .map(row => ({
        PROVIDER_ID:        get(row, 'PROVIDER_ID'),
        PROVIDER_NAME:      get(row, 'PROVIDER_NAME'),
        APPROVAL:           get(row, 'APPROVAL'),
        MONTH:              get(row, 'MONTH'),
        CURRENT_AVG_RATING: get(row, 'CURRENT_AVG_RATING'),
        FILLED_BY:          get(row, 'FILLED_BY'),
        FIRST_10_RATING:    get(row, 'FIRST_10_RATING'),
        RATED_COUNT:        get(row, 'RATED_COUNT'),
        TRAINER:            get(row, 'Trainer', 'TRAINER', 'Trainer::multi-filter', 'TRAINER_MULTI_FILTER'),
        F10_RESULT:         get(row, 'F10 Result', 'F10_RESULT', 'F10_Result'),
        MONTH:              get(row, 'MONTH', 'APPROVAL'),
        APPROVAL_MONTH:     get(row, 'MONTH', 'APPROVAL'),
      }));

    if (!rows.length) { console.log('   ⚠️  trainer_sheet.csv had no valid data rows'); return false; }

    const dateStr = new Date().toUTCString().replace(' GMT', ' UTC');
    const content = [
      '// Auto-generated from trainer_sheet.csv — do not edit manually',
      `// Last updated: ${dateStr}`,
      `var TRAINER_RAW = ${JSON.stringify(rows)};`,
      `var TRAINER_DATE = "${dateStr}";`,
      ''
    ].join('\n');
    fs.writeFileSync(TRAINER_JS, content, 'utf8');
    console.log(`   ✅ trainer_data.js built from CSV  |  ${rows.length} rows`);
    return true;
  } catch(e) {
    console.log('   ⚠️  Could not process trainer_sheet.csv:', e.message);
    return false;
  }
}

async function main() {
  console.log();
  console.log('='.repeat(56));
  console.log('   F10 Partner Performance Dashboard — Launcher');
  console.log('   Full Year 2026 · Auto Refresh');
  console.log('='.repeat(56));

  // Step 1: fetch Redash data
  console.log('\n[1/3] Triggering fresh query run on Redash...');
  const jobId = await triggerRefresh();

  if (!jobId) {
    console.log('   Could not trigger refresh. Trying cached data...');
    const cached = await getCached();
    if (!cached || !cached.rows.length) {
      console.log('\n   ❌ Cannot reach jarvis.urbanclap.com');
      console.log('   Make sure you are on the Urban Company VPN.\n');
      process.exit(1);
    }
    console.log(`   ⚠️  Using cached data from ${cached.retrieved_at.slice(0,10)}`);
    saveData(cached.rows, cached.retrieved_at);
  } else {
    const resultId = await pollJob(jobId, 600000);
    console.log('\n   Fetching results...');
    // Use the specific result ID from the completed job for accurate row count
    const result = resultId ? await getResultById(resultId) : await getCached();
    if (!result || !result.rows.length) {
      console.log('   ❌ Could not retrieve results. Try again in a minute.\n');
      process.exit(1);
    }
    saveData(result.rows, result.retrieved_at);
  }

  // Check for manually-downloaded CSV
  console.log('\n[2/3] Checking for trainer_sheet.csv...');
  if (processTrainerCsv()) {
    console.log('   Trainer data will load from trainer_data.js (skipping Apps Script fetch).');
  } else {
    console.log('   No trainer_sheet.csv found — Trainer tab will load from Apps Script URL (if configured).');
  }

  console.log('\n[3/4] Starting local server...');
  const server = await startServer();

  console.log('\n[4/4] Opening dashboard...');
  const url = `http://localhost:${PORT}/${DASHBOARD}`;
  const cmd = `start "" "${url}"`;
  exec(cmd);
  console.log(`   ✅ Dashboard open at ${url}`);
  console.log('\n   ℹ️  Trainer data loads automatically when you click the tab.');
  console.log('   Keep this window open while using the dashboard.');
  console.log('\n   Press Enter to stop the server and close.\n');
}

main().catch(err => {
  console.error('\n❌ Unexpected error:', err.message);
}).finally(() => {
  process.stdin.resume();
  process.stdin.once('data', () => process.exit(0));
});
